import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service",
    description: "Terms of Service for AgentifyNow.AI"
}

export default function TermsPage() {
    return (
        <div className="max-w-4xl mx-auto px-4 py-8 pt-32 md:pt-40">
            <h1 className="text-3xl font-bold mb-6">Terms of Service – AgentifyNow.AI</h1>
            
            <div className="prose prose-lg max-w-none">
                <p className="mb-6">
                    Welcome to AgentifyNow.AI ("we," "our," or "us").
                    By accessing or using our website, products, or services, you agree to these Terms of Service ("Terms"). 
                    Please read them carefully before using our site or tools. If you do not agree with these Terms, 
                    please do not use our website or services.
                </p>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">1. Overview</h2>
                    <p>
                        AgentifyNow.AI provides AI-powered automation and workflow solutions designed to help businesses streamline processes. 
                        These Terms govern your access to and use of our website, tools, and any related services we provide.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">2. Eligibility</h2>
                    <p>
                        You must be at least 18 years old to use our website or services. By using them, you represent that you have the legal authority to agree to these Terms on behalf of yourself or the entity you represent.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">3. Acceptable Use</h2>
                    <p className="mb-4">You agree not to use our website or services to:</p>
                    <ul className="list-disc pl-6 space-y-1 mb-4">
                        <li>Violate any applicable law or regulation.</li>
                        <li>Upload or transmit malicious code, viruses, or harmful data.</li>
                        <li>Attempt to gain unauthorized access to our systems or networks.</li>
                        <li>Use AI-generated results in a way that violates the rights of others (e.g., intellectual property, privacy, or reputation).</li>
                        <li>Reverse engineer, copy, or resell our proprietary tools or content.</li>
                    </ul>
                    <p>
                        We reserve the right to suspend or terminate access to anyone who violates these Terms.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">4. AI-Generated Content</h2>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Our automation and AI tools are designed to assist users in generating or processing information.</li>
                        <li>Outputs generated by AI are provided "as is" and may contain inaccuracies or errors.</li>
                        <li>You are responsible for reviewing and verifying all AI-generated content before relying on it for business or legal decisions.</li>
                        <li>AgentifyNow.AI does not guarantee that AI outputs will be unique, error-free, or compliant with any specific laws or standards.</li>
                    </ul>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
                    <p className="mb-4">
                        All content on this website — including text, graphics, logos, software, and design — is owned by or licensed to AgentifyNow.AI and protected by copyright and trademark laws.
                    </p>
                    <p>
                        You may not reproduce, distribute, or create derivative works from our materials without prior written permission.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">6. Third-Party Tools & Integrations</h2>
                    <ul className="list-disc pl-6 space-y-2 mb-4">
                        <li>Our services may integrate with or rely on third-party platforms (e.g., automation frameworks, AI providers, analytics tools).</li>
                        <li>We use these tools solely to deliver and improve our services.</li>
                        <li>Each third party is bound by its own privacy and security policies.</li>
                        <li>AgentifyNow.AI is not responsible for the content, functionality, or data practices of external platforms.</li>
                    </ul>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">7. Disclaimers</h2>
                    <p className="mb-4">To the fullest extent permitted by law:</p>
                    <ul className="list-disc pl-6 space-y-1 mb-4">
                        <li>Our services are provided on an "as is" and "as available" basis without warranties of any kind.</li>
                        <li>We do not guarantee that the site or services will be uninterrupted, error-free, or fully secure.</li>
                        <li>We are not responsible for any loss or damage resulting from the use (or inability to use) our website, AI tools, or related services.</li>
                    </ul>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">8. Limitation of Liability</h2>
                    <p>
                        To the maximum extent permitted by law, AgentifyNow.AI and its affiliates shall not be liable for any indirect, incidental, special, consequential, or punitive damages — including lost profits, lost data, or business interruption — arising from or related to your use of our services, even if advised of the possibility of such damages.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">9. Indemnification</h2>
                    <p>
                        You agree to indemnify and hold harmless AgentifyNow.AI, its affiliates, and team members from any claims, damages, or expenses (including legal fees) arising from your misuse of our website, services, or AI tools, or from your violation of these Terms.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">10. Modifications to Services or Terms</h2>
                    <p>
                        We may update or modify our website, tools, or these Terms at any time. Your continued use of our services after such changes constitutes acceptance of the revised Terms.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">11. Governing Law and Jurisdiction</h2>
                    <p>
                        These Terms shall be governed by and construed in accordance with the laws of the Republic of Ecuador.
                        Any dispute arising out of or relating to these Terms shall be resolved before the competent courts of Quito, Ecuador, unless otherwise required by applicable law.
                    </p>
                </section>

                <section className="mb-8">
                    <h2 className="text-2xl font-semibold mb-4">12. Contact Us</h2>
                    <p className="mb-4">
                        If you have questions about these Terms, please contact us at:
                    </p>
                    <div className="space-y-2">
                        <p>📧 <a href="mailto:info@agentifynow.ai" className="text-blue-600 hover:underline">info@agentifynow.ai</a></p>
                        <p>🌐 <a href="https://www.agentifynow.ai" className="text-blue-600 hover:underline">www.agentifynow.ai</a></p>
                    </div>
                </section>
            </div>
        </div>
    );
}